config/routes.rb
Rails.application.routes.draw do

  namespace :api do

  end

  devise_for :users
  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => 'page'
  end

  namespace :api do
    get 'startup', to: 'api#startup'
    get 'records/start_up'
    get 'records/student_check'
    get 'records/check_in'
    get 'records/keep_online'
    get 'records/check_out'
    get 'records/leave_early'
  end

  root 'home#index'

  get 'team_members/import'
  get 'issues/my_issues'

  resources :team_members, concerns: :paginatable
  resources :students, concerns: :paginatable
  resources :issues, concerns: :paginatable

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :team_member
  belongs_to :student
  has_paper_trail
  enum status: [:reported, :in_progress, :missing_description, :closed]
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  before_action :set_issue, except: [:index, :create, :my_issues]
  skip_before_action :authenticate_user!, only:

  def index
    @issues = Issue.order('updated_at DESC').page(params[:page])
    @issue = Issue.new
  end

  def show
  end

  def report

  end

  def my_issues
    @issues = Issue.where(team_member_id: current_user.team_member.id).page(params[:page])
    @issue = Issue.new
    render 'index'
  end

  def create
    @issue = Issue.new(issue_params)
    if @issue.save
      @success = '保存成功'
    else
      @error = show_error @issue
    end
    render 'refresh_issue'
  end

  def edit
  end

  def update
    if @issue.update(issue_params)
      @success = '事务更新成功'
    else
      @error = show_error @issue
    end
    render 'refresh_issue'
  end

  def destroy
    if @issue.destroy
      @success = '删除成功'
    else
      @error = show_error @student
    end
    render 'refresh_issue'
  end

  private

  def set_issue
    @issue = Issue.find(params[:id])
  end

  def issue_params
    params.require(:issue).permit(:title, :description, :team_member_id, :student_id, :status)
  end

end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_changelist.html.erb
<div class="widget-box issue-box">
  <div class="widget-header">
    <h4 class="widget-title lighter smaller">
      <i class="ace-icon fa fa-comment blue"></i>
      <%= issue.title %> - 最后更新于 <%= issue.updated_at %>
    </h4>
  </div>

  <div class="widget-body">
    <div class="widget-main no-padding">
      <div class="dialogs">
        <% issue.versions.each do |version| %>
            <div class="itemdiv dialogdiv">
              <div class="user">
                <%= image_tag('avatar2.png') %>
              </div>
              <div class="body">

                <div class="time">
                  <i class="ace-icon fa fa-clock-o"> </i>
                <span class="green">
                  <%= human_time version.created_at %>
                </span>
                </div>

                <div class="name">
                  <%= version.whodunnit.present? ? version.whodunnit : 'System' %> - <%= version.event %>
                </div>
                <div class="text">
                  <% version.changeset.each do |k, v| %>
                      <div class="issue-changes">
                        <span class="issue-key"><%= k %></span>
                      <span class="issue-value">
                        <span class="old"><%= v[0] %></span> =>
                        <span class="new"><%= v[1] %></span>
                      </span>
                      </div>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>

      </div>

    </div>
    <!-- /.widget-main -->
  </div>
  <!-- /.widget-body -->
</div><!-- /.widget-box -->

app/views/issues/_form.html.erb
<%= form_for issue, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :team_member %><br>
      <%= f.select :team_member_id, options_from_collection_for_select(TeamMember.all, :id, :full_name, issue.team_member_id), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :student %><br>
      <%= f.select :student_id, options_from_collection_for_select(Student.all, :id, :display_name, issue.student_id), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :status %>
      <%= f.select :status, enum_to_options(Issue.statuses), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit '保存', {class: 'btn btn-white btn-default btn-round'} %>
    </div>
<% end %>

app/views/issues/_table.html.erb
<table class="table">
  <thead>
  <tr>
    <th>标题</th>
    <th>描述</th>
    <th>负责人</th>
    <th>状态</th>
    <th>创建于</th>
    <th>更新于</th>
    <th colspan="2">操作</th>
  </tr>
  </thead>
  <tbody>
  <% issues.each do |issue| %>
      <tr>
        <td><%= issue.title %></td>
        <td><%= issue.description.truncate(20) %></td>
        <td><%= issue.team_member.full_name || '' %></td>
        <td><%= issue.status %></td>
        <td><%= issue.created_at.to_formatted_s(:short) %></td>
        <td><%= issue.updated_at.to_formatted_s(:short) %></td>
        <td>
          <%= link_to '更新', edit_issue_path(issue.id), data: {remote: true} %>
        </td>
        <td>
          <%= link_to '详情', issue_path(issue.id), data: {remote: true} %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/issues/edit.js.erb
bootbox.dialog({
    message: "<%=j render :partial => 'form', locals: {issue: @issue}%>",
    title: "编辑 Issue"
});

app/views/issues/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">工单列表</div>
  <div id="js-issues">
    <%= render partial: 'table', locals: {issues: @issues} %>
  </div>
</div>

<div class="col-xs-6">
  <h2>新增一个工单</h2>
  <%= render partial: 'form', locals: {issue: @issue} %>
</div>

app/views/issues/refresh_issue.js.erb
<% unless @success.blank? %>
$('#js-issues').html('<%=j render(partial: 'table', locals: { issues: Issue.order('updated_at DESC').page(1) }) %>');
bootbox.hideAll();
Messenger().success('<%= @success %>');
<% end %>
<% unless @error.blank? %>
Messenger().error('<%= @error %>');
<% end %>

app/views/issues/report.html.erb
<%= 'Hello World' %>

app/views/issues/show.js.erb
bootbox.dialog({
    message: "<%=j render :partial => 'changelist', locals: {issue: @issue}%>",
    title: "Issue 历史纪录"
});