config/routes.rb
Rails.application.routes.draw do

  namespace :api do

  end

  devise_for :users
  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => 'page'
  end

  namespace :api do
    get 'startup', to: 'api#startup'
    get 'records/start_up'
    get 'records/student_check'
    get 'records/check_in'
    get 'records/keep_online'
    get 'records/check_out'
    get 'records/leave_early'
  end

  root 'home#index'

  get 'team_members/import'
  get 'issues/my_issues'

  resources :team_members, concerns: :paginatable
  resources :students, concerns: :paginatable
  resources :issues, concerns: :paginatable

end

app/models/student.rb
class Student < ActiveRecord::Base
  includes Exportable
  enum school: [:site, :bs, :sfs, :sim, :sir, :spa, :scll, :sie, :sis, :ss, :sbf, :law]
  enum sex: [:male, :female]
  # %w{经贸,商学,外语,信息,国关,公管,中文,保险,英语,统计,金融,法学}
  validates :student_number, uniqueness: {message: '不允许重复'}
  has_many :details, dependent: :destroy
  has_one :schedule, dependent: :destroy
  has_many :error_logs, dependent: :destroy
  has_many :issues, dependent: :destroy

  #todo:现在不允许换课,要用detail 来处理,再思考

  def allow_checkin?
    Time.now.wday == self.schedule.weekday ? true : false
  end

  def display_name
    "#{self.student_number} #{self.name}"
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, except: [:index,:create]

  def index
    @students = Student.order('student_number DESC').page(params[:page])
    @student = Student.new
  end

  def show
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      @success = '保存成功'
    else
      @error = show_error @student
    end
    render 'refresh_student'
  end

  def edit
  end

  def update
    if @student.update(student_params)
      @success = '学生信息更新成功'
    else
      @error = show_error @student
    end
    render 'refresh_student'
  end

  def destroy
    if @student.destroy
      @success = '删除成功'
    else
      @error = show_error @student
    end
    render 'refresh_student'
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :student_number, :school, :grade, :student_class, :major, :sex, :phone_number, :dyned_class, :email)
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for student, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :student_number %>
      <%= f.text_field :student_number, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :sex %>
      <%= f.select :sex, enum_to_options(Student.sexes), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :school %>
      <%= f.select :school, enum_to_options(Student.schools), class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :grade %>
      <%= f.text_field :grade, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :student_class %>
      <%= f.text_field :student_class, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :major %>
      <%= f.text_field :major, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.phone_field :phone_number, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :dyned_class %>
      <%= f.text_field :dyned_class, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit '保存', {class: 'btn btn-white btn-default btn-round'} %>
    </div>
<% end %>

app/views/students/_table.html.erb
<table class="table">
  <thead>
  <tr>
    <th>学号</th>
    <th>姓名</th>
    <th>性别</th>
    <th>学院</th>
    <th>年级</th>
    <th>班级</th>
    <th>专业</th>
    <th>电话</th>
    <th>DynEd班级</th>
    <th>Email</th>
    <th>操作</th>
  </tr>
  </thead>
  <tbody>
  <% students.each do |student| %>
      <tr>
        <td><%= student.student_number %></td>
        <td><%= student.name %></td>
        <td><%= enum_to_human student.sex %></td>
        <td><%= enum_to_human student.school %></td>
        <td><%= student.grade %></td>
        <td><%= student.student_class %></td>
        <td><%= student.major %></td>
        <td><%= student.phone_number %></td>
        <td><%= student.dyned_class %></td>
        <td><%= student.email %></td>
        <td>
          <%= link_to '更新', edit_student_path(student.id), data: {remote: true} %>
          |
          <%= link_to '删除', student_path(student.id), data: {confirm: "确定删除#{student.name}吗?", remote: true}, method: :delete %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= paginate students %>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.js.erb
bootbox.dialog({
    message: "<%=j render :partial => 'form', locals: {student: @student}%>",
    title: "编辑学生"
});

app/views/students/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">学生列表</div>
  <div id="js-student">
    <%= render partial: 'table', locals: {students: @students} %>
  </div>
</div>
<h2>新增一个学生</h2>
<div class="col-xs-12">
  <%= render partial: 'form', locals: {student: Student.new} %>
</div>

app/views/students/refresh_student.js.erb
<% unless @success.blank? %>
$('#js-student').html('<%=j render(partial: 'table', locals: { students: Student.order('student_number DESC').page(1) }) %>');
bootbox.hideAll();
Messenger().success('<%= @success %>');
<% end %>
<% unless @error.blank? %>
Messenger().error('<%= @error %>');
<% end %>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>