config/routes.rb
Rails.application.routes.draw do

  namespace :api do

  end

  devise_for :users
  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => 'page'
  end

  namespace :api do
    get 'startup', to: 'api#startup'
    get 'records/start_up'
    get 'records/student_check'
    get 'records/check_in'
    get 'records/keep_online'
    get 'records/check_out'
    get 'records/leave_early'
  end

  root 'home#index'

  get 'team_members/import'
  get 'issues/my_issues'

  resources :team_members, concerns: :paginatable
  resources :students, concerns: :paginatable
  resources :issues, concerns: :paginatable

end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  include Exportable
  validates :email, uniqueness: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, message: 'is not correct'}
  belongs_to :user, touch: true

  def full_name
    "#{self.last_name} #{self.first_name}"
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @team_members = TeamMember.includes(:user).order('id DESC').page(params[:page])
    @team_member = TeamMember.new
    #TODO: 增加权限控制
    respond_to do |format|
      format.html
      format.csv { send_csv_data TeamMember.to_csv, "team_members-#{DateTime.current.to_s(:number)}" }
    end
  end

  def edit
  end

  def update
    if @team_member.update(team_member_params)
      @success = '团队成员更新成功'
    else
      @error = show_error(@team_member)
    end
    @team_members = TeamMember.includes(:user).order('updated_at DESC').page(1)
    render 'refresh_team_member'
  end

  def create
    @team_member = TeamMember.new(team_member_params)
    if @team_member.save
      @success = '保存成功'
    else
      @error = show_error(@team_member)
    end
    @team_members = TeamMember.includes(:user).order('updated_at DESC').page(1)
    render 'refresh_team_member'
  end

  def destroy
    if @team_member.destroy
      @success = '删除成功'
    else
      @error = show_error(@team_member)
    end
  end

  def import
  end

  private
  def set_team_member
    @team_member = TeamMember.find(params[:id])
  end

  def team_member_params
    params.require(:team_member).permit(:first_name, :last_name, :phone_number, :email, :title)
  end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_form.html.erb
<%= form_for team_member, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
    </div>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.submit '保存', {class: 'btn btn-white btn-default btn-round'} %>
    </div>
<% end %>

app/views/team_members/_table.html.erb
<table class="table">
  <thead>
  <tr>
    <th>姓名</th>
    <th>E-mail</th>
    <th>电话</th>
    <th>职位</th>
    <th>级别</th>
    <th>操作</th>
  </tr>
  </thead>
  <tbody>
  <% team_members.each do |team_member| %>
    <tr>
      <td><%= team_member.full_name %></td>
      <td><%= team_member.email %></td>
      <td><%= team_member.phone_number %></td>
      <td><%= team_member.title %></td>
      <td><%= team_member.user.get_role_name if team_member.user.present? %></td>
      <td>
        <%= link_to '更新', edit_team_member_path(team_member.id), data: {remote: true} %> |
        <% unless team_member.email == current_user.email %>
          <%= link_to '删除', team_member_path(team_member.id), data: {confirm: "确定删除#{team_member.full_name}吗?"}, method: :delete %>
          |
        <% end %>
        <%= link_to '授权' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate team_members %>

app/views/team_members/create.html.erb
<h1>TeamMember#create</h1>
<p>Find me in app/views/team_member/create.html.erb</p>

app/views/team_members/edit.js.erb
bootbox.dialog({
    message: "<%=j render :partial => 'form', locals: {team_member: @team_member}%>",
    title: "编辑团队成员"
});

app/views/team_members/import.html.erb
<div class="large-12 large-center columns">
  <h1></h1>
</div>

app/views/team_members/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">成员列表</div>
  <div id="js-team-member">
    <%= render partial: 'table', locals: {team_members: @team_members} %>
  </div>
</div>
<%= render partial: 'form', locals: {team_member: TeamMember.new} %>

app/views/team_members/refresh_team_member.js.erb
<% unless @success.blank? %>
$('#js-team-member').html('<%=j render(partial: 'table', locals: { team_members: @team_members }) %>');
bootbox.hideAll();
Messenger().success('<%= @success %>');
<% end %>
<% unless @error.blank? %>
Messenger().error('<%= @error %>');
<% end %>

app/views/team_members/show.html.erb
<h1>TeamMember#show</h1>
<p>Find me in app/views/team_member/show.html.erb</p>

app/views/team_members/update.js.erb
$("#js-global-modal").append(<%= render :partial => 'form' %>).foundation('reveal', 'open');