config/routes.rb
Rails.application.routes.draw do

  namespace :api do

  end

  devise_for :users
  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => 'page'
  end

  namespace :api do
    get 'startup', to: 'api#startup'
    get 'records/start_up'
    get 'records/student_check'
    get 'records/check_in'
    get 'records/keep_online'
    get 'records/check_out'
    get 'records/leave_early'
  end

  root 'home#index'

  get 'team_members/import'
  get 'issues/my_issues'

  resources :team_members, concerns: :paginatable
  resources :students, concerns: :paginatable
  resources :issues, concerns: :paginatable

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.is_superadmin?
      can :manage, :all
    else
      can :read, :all
    end
  end

  def admin
    can :manage, TeamMember
  end

  def superadmin
    can :manage, all
  end

end

app/models/class_room.rb
class ClassRoom < ActiveRecord::Base
  validates :IP, uniqueness: true
  has_many :details

  def allowed_location?
    early = CFG['allowed_location'][self.location.downcase]['start']
    late = CFG['allowed_location'][self.location.downcase]['end']
    (Time.now.hour >= early && Time.now.hour <= late) ? true : false
  end

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  belongs_to :student
  belongs_to :class_room
end

app/models/error_log.rb
class ErrorLog < ActiveRecord::Base
  belongs_to :student
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :team_member
  belongs_to :student
  has_paper_trail
  enum status: [:reported, :in_progress, :missing_description, :closed]
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :student
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  includes Exportable
  enum school: [:site, :bs, :sfs, :sim, :sir, :spa, :scll, :sie, :sis, :ss, :sbf, :law]
  enum sex: [:male, :female]
  # %w{经贸,商学,外语,信息,国关,公管,中文,保险,英语,统计,金融,法学}
  validates :student_number, uniqueness: {message: '不允许重复'}
  has_many :details, dependent: :destroy
  has_one :schedule, dependent: :destroy
  has_many :error_logs, dependent: :destroy
  has_many :issues, dependent: :destroy

  #todo:现在不允许换课,要用detail 来处理,再思考

  def allow_checkin?
    Time.now.wday == self.schedule.weekday ? true : false
  end

  def display_name
    "#{self.student_number} #{self.name}"
  end

end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  include Exportable
  validates :email, uniqueness: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, message: 'is not correct'}
  belongs_to :user, touch: true

  def full_name
    "#{self.last_name} #{self.first_name}"
  end
end

app/models/term_plan.rb
class TermPlan < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
  allowed_domain = "@#{CFG['allowed_domain']}"
  validates :email, format: {with: /#{allowed_domain}/, message: '验证失败,不是内部用户'}
  attr_accessor :login
  has_one :team_member

  def get_role_name
    ''
  end

  def login=(login)
    @login = login
    self.email = "#{@login}@#{CFG['allowed_domain']}"
  end

  def login
    @login || self.email
  end

  protected
  def self.find_first_by_auth_conditions(warden_conditions)
    warden_conditions[:email] = "#{warden_conditions.delete(:login)}@#{CFG['allowed_domain']}"
    super(warden_conditions)
  end

end

app/models/week_plan.rb
class WeekPlan < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def enum_to_human(enum)
    I18n.t(:"enum.#{enum}", default: enum.to_s.humanize) unless enum.blank?
  end

  def enum_to_options(enum)
    Hash[enum.map { |item| [enum_to_human(item[0]), item[0]] }]
  end

  def send_csv_data(csv_data, filename)
    send_data csv_data.encode('gb2312', :invalid => :replace, :undef => :replace, :replace => '?'),
              :type => 'text/csv; charset=iso-8859-1; header=present',
              :disposition => "attachment; filename=#{filename}.csv"
  end

  def icon_for(flash_type)
    {
        :success => '&#xe613;',
        :error => '&#xe614;',
        :alert => '&#xe618;',
        :notice => '&#xe616;'
    }[flash_type.to_sym] || '&#xe616;'
  end

  def alert_class_for(flash_type)
    {
        :success => 'alert-success',
        :error => 'alert-danger',
        :alert => 'alert-warning',
        :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def ilink_to(text, path, options = {}) #带iconfont的lint_to
    icon_class = options[:icon]
    options.delete(:icon)
    link_to path, options do
      content_tag(:i, '', class: "fa fa-#{icon_class}") + content_tag(:span, " #{text}")
    end
  end

  def module_name #返回controller name (如果controller在目录中，则返回该目录名)
    controller_path.split('/')[0]
  end

  def menu_link_to(text, path, options={})
    link_to path, options do
      content_tag(:i, '', class: 'menu-icon fa fa-caret-right') + content_tag(:span, "#{text}") + content_tag(:b, '', class: 'arrow')
    end
  end

  def human_time(time)
    "#{distance_of_time_in_words(time, Time.now, include_seconds: true)}前" if time.present?
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert-box alert radius">
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= render partial: 'shared/head' %>
</head>

<body id="<%= "#{controller_name}-#{action_name}" %>" class="no-skin mo-<%= module_name %>">
<div class="navbar" id="navbar">
  <%= render partial: 'shared/navbar' %>
</div>
<div class="main-container" id="main-container">
  <div class="sidebar responsive" id="sidebar">
    <%= render partial: 'shared/side_bar' %>
  </div>

  <div class="main-content">

    <div class="breadcrumbs" id="breadcrumbs">
      <%= render partial: 'shared/breadcrumbs' %>
    </div>
    <div class="page-header">
      <%= render partial: 'shared/page_header' %>
    </div>
    <div class="page-content">
      <!-- setting box goes here if needed -->
      <div class="row">
        <div class="col-xs-12">
          <%= render partial: 'shared/flash_message' %>
          <%= yield %>
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->

    </div>
    <!-- /.page-content -->
  </div>
  <!-- /.main-content -->
  <%= render partial: 'shared/footer' %>
</div>
<!-- /.main-container -->
</body>
</html>

app/views/layouts/blank_body.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= render partial: 'shared/head' %>
</head>

<body id="<%= "#{controller_name}-#{action_name}" %>" class="mo-<%= module_name %>">
<%= render partial: 'shared/flash_message' %>
<%= yield %>
</body>
</html>

app/views/layouts/blank_body_with_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= render partial: 'shared/head' %>
</head>

<body id="<%= "#{controller_name}-#{action_name}" %>" class="mo-<%= module_name %>">
<%= render partial: 'shared/navbar' %>
<%= yield %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= render partial: 'shared/head' %>
</head>

<body id="<%= "#{controller_name}-#{action_name}" %>" class="mo-<%= module_name %> login-layout blur-login">

<div class="main-container">
  <div class="main-content">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <%= yield %>
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.main-content -->
</div>
<!-- /.main-container -->


</body>
</html>

app/views/shared/_breadcrumbs.html.erb
<ul class="breadcrumb">
  <li>
    <i class="ace-icon fa fa-home home-icon"></i>
    <a href="#"><%= controller_name.capitalize %></a>
  </li>
  <li class="active">
    <%= action_name.capitalize %>
  </li>
</ul>

app/views/shared/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, {class: "alert #{alert_class_for name}", role: 'alert'} %>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="renderer" content="webkit"/>
  <title><%= content_for?(:title) ? yield(:title) : 'Seagull Platform' %></title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

app/views/shared/_navbar.html.erb
<div id="navbar" class="navbar navbar-default">
  <div id="navbar-container" class="navbar-container">

    <!-- toggle buttons are here or inside brand container -->

    <div class="navbar-header pull-left">
      <a href="#" class="navbar-brand">
        <small>
          <i class="fa fa-cloud"></i>
          Seagull Platform
        </small>
      </a>
    </div>
    <!-- /.navbar-header -->


    <div class="navbar-buttons navbar-header pull-right ">
      <ul class="nav ace-nav">
        <li class="light-blue">
          <a data-toggle="dropdown" href="#" class="dropdown-toggle" aria-expanded="false">
            <%= image_tag('avatar2.png', {class: 'nav-user-photo'}) %>
            <span class="user-info">
									<small>Welcome,</small>
              <%= get_member.first_name %>
            </span>
            <i class="ace-icon fa fa-caret-down"></i>
          </a>
          <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
            <li><a href="#">个人信息</a></li>
            <li><a href="#">账户管理</a></li>
            <li class="divider"></li>
            <li><%= link_to('退出登录', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-buttons -->


    <nav class="navbar-menu pull-left">
      <!-- optional menu & form inside navbar -->
    </nav>
    <!-- /.navbar-menu -->

  </div>
  <!-- /.navbar-container -->
</div><!-- /.navbar -->

app/views/shared/_page_header.html.erb
<!--<h1>-->
  <!--控制面板-->
  <!--<small>-->
    <!--<i class="ace-icon fa fa-angle-double-right"></i>-->
    <!--统计与详情-->
  <!--</small>-->
<!--</h1>-->

app/views/shared/_side_bar.html.erb
<div id="sidebar" class="sidebar responsive">
  <script type="text/javascript">
      try {
          ace.settings.check('sidebar', 'fixed')
      } catch (e) {
      }
  </script>


  <ul class="nav nav-list">
    <li class="">
      <a href=<%= root_path %>>
        <i class="menu-icon fa fa-tachometer"></i>
        <span class="menu-text"> 控制面板 </span>
      </a>

      <b class="arrow"></b>
    </li>
    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="menu-icon fa fa-list-alt"></i>
        <span class="menu-text">事务处理</span>

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">

        <li class="">
          <%= menu_link_to('工单列表', issues_path) %>
        </li>

        <li class="">
          <%= menu_link_to('我的工单', issues_my_issues_path) %>
        </li>

        <li class="">
          <%= menu_link_to('统计报表', '#') %>
        </li>

        <li class="">
          <%= menu_link_to('规则设置', '#') %>
        </li>

        <li class="">
          <%= menu_link_to('知识库', '#') %>
        </li>
      </ul>
    </li>

    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="menu-icon fa fa-users"></i>
							<span class="menu-text">
                学生管理
							</span>

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">

        <li class="">
          <%= menu_link_to('学生列表', students_path) %>
        </li>

        <li class="">
          <%= menu_link_to('导入学生', '#') %>
        </li>

        <li class="">
          <%= menu_link_to('导出学生', '#') %>
        </li>

        <li class="">
          <%= menu_link_to('上课记录', '#') %>
        </li>
      </ul>
    </li>

    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="menu-icon fa fa-desktop"></i>
        <span class="menu-text">值班管理</span>

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">
        <li class="">
          <%= menu_link_to('时间录入', '#') %>
        </li>
        <li class="">
          <%= menu_link_to('值班安排', '#') %>
        </li>
        <li class="">
          <%= menu_link_to('值班调整', '#') %>
        </li>
        <li class="">
          <%= menu_link_to('值班签到', '#') %>
        </li>
        <li class="">
          <%= menu_link_to('值班统计', '#') %>
        </li>
      </ul>
    </li>

    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="menu-icon fa fa-sitemap"></i>
        <span class="menu-text"> 团队管理 </span>

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">
        <li class="">
          <%= menu_link_to('成员列表', team_members_path) %>
        </li>
        <li class="">
          <%= menu_link_to('考勤统计', '#') %>
        </li>
        <li class="">
          <%= menu_link_to('通知管理', '#') %>
        </li>
        <li class="">
          <%= menu_link_to('绩效管理', '#') %>
        </li>
      </ul>
    </li>

    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="menu-icon fa fa-institution"></i>
        <span class="menu-text"> 上课记录 </span>

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">
        <li class="">
          <%= menu_link_to('查看记录', team_members_path) %>
        </li>
        <li class="">
          <%= menu_link_to('记录处理', '#') %>
        </li>
      </ul>
    </li>

    <li class="">
      <a href="#" class="dropdown-toggle">
        <i class="menu-icon fa fa-wrench"></i>
        <span class="menu-text"> 系统管理 </span>

        <b class="arrow fa fa-angle-down"></b>
      </a>

      <b class="arrow"></b>

      <ul class="submenu">
        <li class="">
          <%= menu_link_to('教室管理', team_members_path) %>
        </li>
        <li class="">
          <%= menu_link_to('系统设置', '#') %>
        </li>
      </ul>
    </li>
  </ul>
  <!-- /.nav-list -->


</div>